<?php

namespace AppBundle\Repository;

/**
 * ElementVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementVenteRepository extends \Doctrine\ORM\EntityRepository
{
}
