<?php

namespace AppBundle\Repository;

/**
 * TypeFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
